# Generated by Django 4.2 on 2023-07-19 19:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, null=True, verbose_name='Название фильма')),
                ('movie_image', models.ImageField(null=True, upload_to='movie_images', verbose_name='Картинка фильма')),
                ('movie_genre', models.CharField(max_length=100, null=True, verbose_name='Жанр фильма')),
                ('movie_tag', models.TextField(null=True, verbose_name='Теги фильма')),
                ('movie_published', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2050)], verbose_name='Год выпуска')),
                ('movie_description', models.TextField(verbose_name='Описание фильма')),
                ('top_movie', models.BooleanField(default=False)),
                ('movie_like', models.ManyToManyField(default=0, related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки фильма')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
