# Generated by Django 4.2 on 2023-07-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_like',
        ),
    ]
